services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - uploads_data:/app/uploads
      - private_uploads_data:/app/private_uploads

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
    - ./frontend:/app
    - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data:
  private_uploads_data:
  redis_data:
