services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
