---
- name: Validate Nginx configuration
  ansible.builtin.command: /usr/sbin/nginx -t
  changed_when: false
  listen: Reload Nginx

- name: Reload Nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
  listen: Reload Nginx
